PREFIX : <http://purl.org/mrrobson9/rag#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT
  ?q
  ?retrievalExec
  ?rerankExec
  ?rerankerConf
  ?rc
  (STR(?finalRankV) AS ?finalRank)
  (STR(?finalScoreV) AS ?finalScore)
WHERE {
  VALUES ?q { :q1 }
  
  ?q :triggers ?retrievalExec .
  
  # Verifica se houve reranking
  ?retrievalExec :partOf ?rerankExec .
  ?rerankExec a :RerankingExec .
  
  # Pega a configuração do reranker (pela Retrieval ou pelo RerankerExec)
  ?rerankExec (:uses|:uses_1|:uses_2) ?rerankerConf .
  ?rerankerConf a :RerankerConfig .
  
  # Para pegar os chunks, temos que passar pelo Contexto!
  ?retrievalExec (:creates|:creates_1) ?ctx .
  ?ctx :hasItem ?rc .
  
  # Pega os scores finais do Rerank (se existirem)
  OPTIONAL { ?rc :finalRank ?finalRankV }
  OPTIONAL { ?rc :finalScore ?finalScoreV }
}